name: Terraform Apply

on: 
  push: 
    branches: [ main ]
  pull-request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.SERVICE_PRINCIPAL_APPID}}
      ARM_CLIENT_SECRET: ${{secrets.SERVICE_PRINCIPAL_PASSWORD}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_SUBSCRIPTION_TENANT_ID}}
      TF_VAR_appId: ${{secrets.SERVICE_PRINCIPAL_APPID}}
      TF_VAR_password: ${{secrets.SERVICE_PRINCIPAL_PASSWORD}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
